#!/bin/bash

echo "🚀 Create New GitHub Repository for AI Terminal Project"
echo "========================================================"
echo ""

echo "📋 Follow these steps to create a new repository:"
echo ""
echo "1. Go to: https://github.com/new"
echo "2. Repository name: ai-terminal-web-interface"
echo "3. Description: Production-ready AI Terminal with web interface, voice commands, and advanced security tools"
echo "4. Choose Public or Private"
echo "5. IMPORTANT: Don't check any boxes (README, .gitignore, license)"
echo "6. Click 'Create repository'"
echo ""
echo "After creating the repository, run these commands:"
echo ""
echo "# Add the new remote (replace YOUR_USERNAME with your GitHub username)"
echo "git remote add origin https://github.com/YOUR_USERNAME/ai-terminal-web-interface.git"
echo ""
echo "# Push to the new repository"
echo "git push -u origin ai-terminal-clean"
echo ""
echo "🔐 After pushing, restore your real API keys:"
echo "cp config/ultra_config.ini.backup config/ultra_config.ini"
echo ""
echo "🎉 Your AI Terminal project will then be live on GitHub!"